services:
  php:
    container_name: books-db
    image: mckillem/books-db
    build: build/php
    volumes:
      - ../:/var/www/html
    ports:
      - "8088:80"
    environment:
      - NETTE_DEBUG=1
#      - COMPOSER_AUTH=${COMPOSER_AUTH}
    links:
      - database

  database:
    container_name: books-db_db
    image: mckillem/books-db_db
    build: build/database
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: books-db
    volumes:
      - ./build/database/01_create.sql:/docker-entrypoint-initdb.d/01_create.sql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8089:80"
    environment:
      - PMA_HOST=database
      - PMA_USER=test
      - PMA_PASSWORD=test